[tool.black]
line-length = 110
target-version = ['py310']

[tool.isort]
line_length = 110
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.mypy]
ignore_missing_imports = true

[tool.flake8]
max-line-length = 110
